### ISSUE TITLE
video CAN’T autoplay hide the controls

### ISSUE THREAD

**Issue by eteled126** [peiche/recover#18]
Hi，Peiche! Thanks for the great and lightweight theme.

Recently, I found a problem :

I want a video auto play without controls panel on my page，i add the video through Aesop Story Engine, self source, OFF the "Disable video on Mobile Devices", ON the"Autoplay",  OFF the "Video Controls"——It works correctly on the desktop, but not on the phone: the video doesn't load, it just shows a frame image, even if you click on it, it will not play.

I tried many times and found, Only when the "Video Controls" option is “ON”, it would play automatically on the phone.

Hide the "Video Controls" and make the video auto play on the phone,how can I do that?

my WP\Cover2\AesopStoryEngine have been upgraded to the latest version. my phone：xperia Z5

Mobile browser access reappears.the page：
http://wwweb.men/web/2131.html

**Comment by peiche** [comment]
This is an issue with Aesop Story Engine, not Cover2. As such, I'm closing this issue. You can, however, raise this issue on the plugin's page: https://github.com/hyunsupul/aesop-core/issues/new

I did take a look at the ASE video component source, and [this is the code responsible](https://github.com/hyunsupul/aesop-core/blob/master/public/includes/components/component-video.php#L340-L358). For self-hosted videos, there are two checks. The first is for "disable for mobile" is off, but the second is for the WordPress function [wp_is_mobile](https://codex.wordpress.org/Function_Reference/wp_is_mobile). There is no way to override this unless the plugin's source is changed.

**Comment by eteled126** [comment]
Thank you for your reply. I will go there to feedback the issue.

Another problem, when my tag/category is in Chinese, Cover2 shows a mess of code on the page.Does Cover2  not support non-eng languages?

Related pages:
http://wwweb.men/web/2131.html

**Comment by peiche** [comment]
That's a bug. I'll fix that in the next update. Do you mind raising a separate issue for it?

**Comment by eteled126** [comment]
Ok
