### ISSUE TITLE
Non-Eng languages CAN'T  show correctly in tag and category

### ISSUE THREAD

**Issue by eteled126** [peiche/recover#20]
Love Cover2 and a problem:
When my tag/category is in Chinese, Cover2 shows a mess of code on the page like this:
http://wwweb.men/web/2131.html

Would it be fixed ? please!

**Comment by peiche** [comment]
This should be fixed in v1.1.2, which is live on wordpress.org now. Please update your theme and let me know.

**Comment by eteled126** [comment]
It works! the chinese tag/cate have been correctly displayed in the latest theme.
Thank you a lot.
