### ISSUE TITLE
Mess of code again，on the featured picture

### ISSUE THREAD

**Issue by eteled126** [peiche/recover#22]
Warning: sprintf(): Too few arguments in /home/ftp/g/grip/wwwroot/wwweb/wp-content/themes/cover2/inc/template-tags.php on line 28

have a look at：
http://wwweb.men/dog/%E4%B8%9C%E9%A3%8E%E8%A7%A3%E5%86%BB.html

**Comment by peiche** [comment]
I updated the version on wordpress.org. Let me know if this fixes the issue.

**Comment by eteled126** [comment]
well done, the last version theme has fixed it! thank you.
