### ISSUE TITLE
The header navigation bar of author page getting all white from p2

### ISSUE THREAD

**Issue by eteled126** [peiche/recover#26]
Hey, I open the author page,  the page 1  is all right, from the second page, the header navigation bar is getting all **white**, can't show the site title, logo, search, and menu.

The white navigation,  (dont scroll the page):
http://wwweb.men/author/ganymede/page/2

**Comment by peiche** [comment]
Version 1.2.1 (just pushed to wp.org) should fix this.

**Comment by eteled126** [comment]
bingo! thanks.
