### ISSUE TITLE
button superimposed again

### ISSUE THREAD

**Issue by eteled126** [peiche/recover#30]
Buttons in two rows on phone :

<img src="https://s1.ax1x.com/2018/03/30/9vwQTH.png" alt="9vwQTH.png" border="0" />

**Comment by eteled126** [comment]
I have updated to the 1.3.0, but the buttons still:
<img src="https://s1.ax1x.com/2018/04/11/CAK7Js.png" alt="CAK7Js.png" border="0" />

**Comment by peiche** [comment]
Would you mind providing me a link to this page?

**Comment by eteled126** [comment]
http://wwweb.men/dog/3.html

**Comment by eteled126** [comment]
fixed!
