### ISSUE TITLE
how to set the accent color accurately

### ISSUE THREAD

**Issue by eteled126** [peiche/recover#34]
hello! I want to change the color of the theme, make the accent and navbar colors the same, but I can't control the accent color accurately, 

I tried several times, moving the slider slowly from left to right, but failed to find the same color as the navigation, which was discouraging.

Ask if it is convenient to set the accent color, such as filling in a value directly like #37b2a6?

<img src="https://s1.ax1x.com/2018/06/05/C7QeyR.png" alt="C7QeyR.png" border="0" />

**Comment by peiche** [comment]
Unfortunately, this is not currently possible. The navbar color allows any color as its background and sets the text color to white or black accordingly, but the accent color is applied to links on the site, so its hue is not changeable.

The best way to currently set the two colors to be identical would be to set the accent color, then using your browser's web inspector, getting the hexadecimal color and pasting that in for the navbar color.
