### ISSUE TITLE
Quote post on homepage issue

### ISSUE THREAD

**Issue by eteled126** [peiche/recover#41]
When a post's format is Quote, It shows on the home page as follows, no title, no content:
<a href="https://imgchr.com/i/F59Hvn"><img src="https://s2.ax1x.com/2019/01/01/F59Hvn.md.png" alt="F59Hvn.png" border="0" /></a>

**Comment by peiche** [comment]
The idea is that you'd have an actual quote in the post somewhere. That gets stripped out of the main content and displayed in the summary for post list views, like the homepage, and in the header of the single post view.

**Comment by eteled126** [comment]
Your explanation makes me understand. thanks!
I chose the Quote format because I wanted to publish a paragraph from a book as a post......so I meet this (issue) that's not a issue.

**Comment by peiche** [comment]
You can definitely still do that. Just make sure it's in a `<blockquote>` element. The quote will be displayed in the header if you choose the Quote post format.
